# Site settings
title: Mario Robayo
email: mrobayo@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Targeting clean coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mrobayo.github.io/" #
github_username:  mrobayo
twitter_username: MaRobayoAyala

# Build settings
#theme: minima
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.20.2"

breadcrumbs: false
timezone: America/Chicago

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - _pages
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom tags
subtitle: "Software Developing Experiences & Post Reviews"
name: "Mario Robayo"
logo: /assets/images/puzzle-icon.png
masthead_title: "Mario Robayo"
teaser: /assets/images/coding.png

author:
  name     : "Mario Robayo"
  avatar   : "/assets/images/11372276.png"
  bio      : "Software Engineering & Family Guy."
  location : "Guayaquil, ECUADOR"


social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://www.linkedin.com/in/mario-robayo/"
    - "https://gab.com/mario_ec/"
    - "https://twitter.com/MaRobayoAyala"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MaRobayoAyala"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mrobayo"
    - label: "Linked-In"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mario-robayo/"

#Searching
search: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
